### ISSUE TITLE
All apps Grid set 4, Allapps UI is not good.

### ISSUE THREAD

**Issue by workjm** [klinker24/Android-Blur-Launcher#1]
I find one ui issue.
All apps Grid set 4, Allapps left and right is not aligned.

**Comment by klinker24** [comment]
this is coming directly from Google's Launcher3, installing that, you see the same issue.

I will look into what would be causing it.

**Comment by klinker24** [comment]
https://github.com/klinker24/Android-Blur-Launcher/commit/d3667ca814884ebe8bb7d63ebba434e1621b15ea

**Comment by workjm** [comment]
thanks,it's ok.
