### ISSUE TITLE
Option to disable pages

### ISSUE THREAD

**Issue by nazar-pc** [klinker24/Android-Blur-Launcher#10]
I was looking for Open Source launcher that issimple, but convenient. Something like Pixel launcher, but without Google assistant hardcoded.
I found this launcher pretty interesting with basic jestures support, but I don't need any pages, would be nice to have a switch to remove them from home page scrolling on hhe left.

**Comment by klinker24** [comment]
This isn't something that I am going to add to the launcher, sorry. That is pretty much the main feature of what I have made here.

It would be extremely easy for you to fork and disable though. The pages on the side run through a navigation drawer. Even if you didn't want to remove any code, you could lock that drawer shut with one line of code in the `Launcher` class

**Comment by nazar-pc** [comment]
I'm not a Java developer, so even if I can do that, maintaining a fork would be too much of an effort for me.

**Comment by klinker24** [comment]
You could just clone it and make the change locally as well. You can see examples of locking the drawer inside the `Launcher` activity already. Just lock it shut in the onCreate method.

**Comment by nazar-pc** [comment]
It would become tedious to update when new upstream versions appear instead of just getting updates through the store automatically, not an option for me.

**Comment by klinker24** [comment]
Ok sorry.
