### ISSUE TITLE
Allow bigger widgets

### ISSUE THREAD

**Issue by nazar-pc** [klinker24/Android-Blur-Launcher#11]
Here you can see some random widget in its max size, however, here is still some space on top unused, can you make so that widgets can be resized even higher? My grid has 8 rows if it is important.
![tmp_3692-screenshot_20161209-0134251308992288](https://cloud.githubusercontent.com/assets/928965/21032146/225db664-bdb0-11e6-8522-577f93925d4c.png)

**Comment by YAJATapps** [comment]
If the developer of blur launcher apply this code your problem will be solved.
https://github.com/CyanogenMod/android_packages_apps_Trebuchet/commit/fe70926e116fca0d84b3642aae3fe6c68d6c7264
You have to just not apply reload flags and instead of that settings provider use appsettings.
If you did not understood then feel free to ask.

**Comment by klinker24** [comment]
Sorry, but that commit doesn't have anything to do with this issue

**Comment by YAJATapps** [comment]
It is a commit which hides search bar
The way you hide it leaves space on top
Wait 5 minutes I send you photos of my launcher

**Comment by YAJATapps** [comment]
![screenshot_20161226-223707](https://cloud.githubusercontent.com/assets/17001098/21484606/d94ce0d4-cbbb-11e6-93d9-dccda9b7c1b9.png)
![screenshot_20161226-223659](https://cloud.githubusercontent.com/assets/17001098/21484628/0ac57a5e-cbbc-11e6-81a9-0d15fc5f67de.png)
This is difference after I applied it

**Comment by nazar-pc** [comment]
Looks better

**Comment by klinker24** [comment]
Alright, I would be more than willing to accept a pull request

**Comment by YAJATapps** [comment]
I know some programming but I don:'t know using github except downloading zip and commenting
Please tell me how to do that and I will send you that commits

**Comment by YAJATapps** [comment]
OK got it will try to send you in 1 or 2 hours if my dad does not put modem off😁

**Comment by YAJATapps** [comment]
My launcher and that commit were marshmallow
Blur is nougat 
So forget that 2 hr message 
I am trying to implement in nougat.
will post as soon as it complete

**Comment by YAJATapps** [comment]
Not tested but try to apply this and tell it works or not
https://github.com/YAJATapps/Android-Blur-Launcher/commit/62966036e2fb2187b6694a228c48b6624ff4a38c

**Comment by klinker24** [comment]
Thanks, I have merged your PR.
