### ISSUE TITLE
want this change in launcher. show n attached image.

### ISSUE THREAD

**Issue by ibadurrahmantalha** [klinker24/Android-Blur-Launcher#27]
i want all 5 icons in this panel by default when launcher is install and apply by first time. how can i do it. please help me.
![device-2017-05-03-163335](https://cloud.githubusercontent.com/assets/28347729/25659175/066ad120-3020-11e7-9220-61487d603f43.jpg)

**Comment by klinker24** [comment]
That isn't something that I am going to bring into the launcher, but if you want to change it yourself, there are defualt settings for different configuration types (screen size/orientation), that you can find links to, from the [AppSettings](https://github.com/klinker24/Android-Blur-Launcher/blob/master/app/src/main/java/xyz/klinker/blur/addons/settings/AppSettings.java) class

**Comment by ibadurrahmantalha** [comment]
please help me. i am not a developer. i just want 5 apps to be added by default in Dock. from AppSettings class we only change size and count etc. how can i add apps like in above screen shots. thanks for helping us.
