### ISSUE TITLE
Remove the Grid from the Homescreen

### ISSUE THREAD

**Issue by AruLNadhaN** [klinker24/Android-Blur-Launcher#3]
I'm trying to remove the grid for the Icons in the Homescreen. I tried tweaking the `AllAppsGridAdapter` & AllAppsRecyclerView. But i can't remove the Grid from the Homescreen . 
Can u show some pointers or guide me how to acheive it ?

**Comment by klinker24** [comment]
The home screen runs off the `Workspace` class, the all apps things are for the all apps drawer, not the home screen.

Can't say much more than that about it though, I think it would be a huge undertaking to completely remove the grid and I am not sure how it would work or how you could store those icons in the database
